# Form implementation generated from reading ui file 'exit.ui'
#
# Created by: PyQt5 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 229)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(125, 125, 125);\n"
"    border: 4px solid rgb(255, 255, 255);\n"
"    \n"
"\n"
"}")
        self.bt_cancel = QtWidgets.QPushButton(Dialog)
        self.bt_cancel.setGeometry(QtCore.QRect(120, 130, 93, 28))
        self.bt_cancel.setObjectName("pushButton")
        self.bt_confirm = QtWidgets.QPushButton(Dialog)
        self.bt_confirm.setGeometry(QtCore.QRect(240, 130, 93, 28))
        self.bt_confirm.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 50, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 80, 191, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "提醒"))
        self.bt_cancel.setText(_translate("Dialog", "取消"))
        self.bt_confirm.setText(_translate("Dialog", "确认"))
        self.label.setText(_translate("Dialog", "是否要离开游戏"))
        self.label_2.setText(_translate("Dialog", "离开游戏后将返回标题界面"))
